#!/bin/bash
#####################################################################################################
#                                     Lidarr Automated Downloader                                   #
#                                    (Powered by: Deezloader Remix)                                 #
#                                       Credit: RandomNinjaAtk                                      #
#####################################################################################################
#                                           Instructions                                            #
#                                                                                                   #
#  1. Configure the settings below                                                                  #
#  2. Execute script from linux cli with the following command:                                     #
#     bash lidarr-automated-downloader.bash                                                        #
#####################################################################################################

############ Paths
downloaddir="/downloads/deezloaderremix" # Deezloader download directory location
beetsunmatcheddirectory="/music/unmatched" # Beets unmatched file directory location
beetsconfig="/config/scripts/beets/config.yaml" # Beets configuration file
beetslibraryfile="/config/scripts/beets/library.blb" # Beets library file
beetslog="/config/scripts/beets/beets.log" # Beets log file

############ Lidarr Settings
LidarrUrl="http://127.0.0.1:8686" # Set domain or IP to your Lidarr instance including port. If using reverse proxy, do not use a trailing slash. Ensure you specify http/s.
LidarrApiKey="$(grep "<ApiKey>" /config/config.xml | sed "s/\  <ApiKey>//;s/<\/ApiKey>//")" # Lidarr API key.

############ Download Settings
deezloaderurl="http://127.0.0.1:1730" # Url to the download client
downloadmethod="album" # album or track :: album method will fallback to track method if it runs into an issue
enablefallback="true" # enables fallback to lower quality if required...
LyricType="all" # all or clean or explicit :: sets the desired lyric type for downloads, all is explicit albums preferred
downloadalbums="true" # true = enabled :: Enables downloading deezer albums that are categorized by deezer as "Album" release type
downloadcompilations="true" # true = enabled :: Enables downloading deezer albums that are categorized by deezer as "Compilation" release type
downloadeps="true" # true = enabled :: Enables downloading deezer albums that are categorized by deezer as "EP" release type
downloadsingles="true"  # true = enabled :: Enables downloading deezer albums that are categorized by deezer as "Single" release type
VerifyTrackCount="true" # true = enabled :: This will verify album track count vs dl track count, if tracks are found missing, it will skip import...
dlcheck=2 # Set the number to desired wait time before checking for completed downloads (if your connection is unstable, longer may be better)
albumtimeoutpercentage=8 # Set the number between 1 and 100 :: This number is used to caculate album download timeout length by multiplying Album Length by ##%
tracktimeoutpercentage=25 # Set the number between 1 and 100 :: This number is used to caculate  track download timeout length by multiplying Track Length by ##%

############ File Options
quality="flac" # flac or mp3 or opus or aac or alac :: Downloads flac or mp3 and then converts to requested format
upgrade="false" # true = enabled :: Enables or Disables upgrading dl quality based on quality type and bitrate changes.
bitrate="192" # bitrate quality for OPUS and AAC formats only
TagWithBeets="false" # true = enabled :: tag files with beets for better lidarr matching
KeepOnlyBeetsMatched="false" # true = enabled :: only keep files that could be successfully matched with beets (keeps really clean library with perfect matches)
MoveBeetsUnMatched="false" # true = enabled :: Moves unmatched beets files to a alternate location for safe keeping
BeetsDeDupe="false" # true = enabled :: Prevents clearing database to allow beets to filter duplicate matches 
replaygaintaggingflac="true" # true = enabled :: Adds replaygain audio normalization tags to flac files
replaygaintaggingopus="false" # true = enabled :: Adds replaygain audio normalization tags to opus files

############ Other Options
debug="false" # true = enabled :: Increases cli output for diagnosing
dailycheck="false" # true = enabled :: Enabling this will prevent checking artitsts that are found in the "daily.log" file, best used with a cron job to clear this file once per day

